### PR TITLE
Handle old pods without network selection elements

### LINKED ISSUE #43: [BUG] cannot hotplug when the "old" pod does not have network-selection-elements
**Describe the bug**
It currently is impossible to hotplug interfaces into a pod that does **not** feature any network selection elements - `k8s.v1.cni.cncf.io/networks`.

**Expected behavior**
It should be possible to hotplug interfaces into a pod without network-selection-elements.

**To Reproduce**
1. Provision the following pod: 
```yaml
apiVersion: v1
kind: Pod
metadata:
  labels:
    app: tiny-winy-pod
  name: tiny-winy-pod
spec:
  containers:
  - command:
    - /bin/ash
    - -c
    - 'trap : TERM INT; sleep infinity & wait'
    image: k8s.gcr.io/e2e-test-images/agnhost:2.26
    imagePullPolicy: IfNotPresent
    name: samplepod
```
2. Hot-plug an interface into it - add the following annotation:
```yaml
k8s.v1.cni.cncf.io/networks: '[{"name":"tenant-network","namespace":"ns1","mac":"02:03:04:05:06:07","interface":"ens58"}]'
```
3. It'll fail to add the interface, and the network-status will not feature this new attachment.

### PR DESCRIPTION
**Pull request by maiqueb**
**What this PR does / why we need it**:
This PR allows hot-plugging interfaces into a pod without any `network-selection-elements`.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #43

**Special notes for your reviewer** *(optional)*:

### CODE REVIEW

File: pkg/controller/pod.go [hunk 1]
```diff
@@ -347,7 +347,10 @@ func (pnc *PodNetworksController) updatePodNetworkStatus(pod *corev1.Pod, newIfa
 func networkSelectionElements(podAnnotations map[string]string, podNamespace string) ([]*nadv1.NetworkSelectionElement, error) {
 	podNetworks, ok := podAnnotations[nadv1.NetworkAttachmentAnnot]
 	if !ok {
-		return nil, fmt.Errorf("the pod is missing the \"%s\" annotation on its annotations: %+v", nadv1.NetworkAttachmentAnnot, podAnnotations)
+		return []*nadv1.NetworkSelectionElement{}, nil
```
Comment (phoracek) [inline pkg/controller/pod.go:350]: I think this could be simplified by using

```go
if !ok || podNetworks == "" {
   return []*nadv1.NetworkSelectionElement{}, nil
}
```

File: e2e/client/types.go [hunk 2]
```diff
@@ -230,14 +230,14 @@ func podMeta(podName string, namespace string, label map[string]string, annotati
...
-
-	currentNetworkSelectionElements, err := annotations.ParsePodNetworkAnnotations(currentNetworkSelectionElementsString, pod.GetNamespace())
-	if err != nil {
-		return ""
+	if wasFound {
+		var err error
+		currentNetworkSelectionElements, err = annotations.ParsePodNetworkAnnotations(currentNetworkSelectionElementsString, pod.GetNamespace())
+		if err != nil {
+			return ""
+		}
```
Comment (phoracek) [inline e2e/client/types.go:240]: Could you extract this part to its own function? I think that the logic looking up and parsing the annotation (if any) is bloating this function (where I would like to read "get elements, update elements, marshal elements").

**Review by phoracek — COMMENTED** [review]
Two tasty nits, the PR looks good. Having the issue  as a reference was helpful

File: e2e/client/types.go (hunk 2 above)
Comment (maiqueb) [reply e2e/client/types.go]: Done.

File: pkg/controller/pod.go (hunk 1 above)
Comment (maiqueb) [reply pkg/controller/pod.go:350]: Done.

**Review by maiqueb — COMMENTED** [review]
Thanks for the review @phoracek .

**Review by phoracek — APPROVED** [review]
/lgtm
